---
language: java

cache:
 directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

#use this distrib for actual java version
#dist: trusty

#matrix:
# include:
#  - os: linux
#    dist: trusty
#    sudo: required
#  - os: osx
#  - os: windows

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - alien
      
addons:
  sonarcloud:
    organization: "antonmykolaienko-github" # the key of the org
    #token:
     # secure: ********* # encrypted value of your token

jdk:
 - oraclejdk8
 
install:
 - sudo apt-get update 
 - sudo apt-get install rpm

script: 
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
 #- sonar-scanner
 #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar