---
language: java

cache:
 directories:
  - $HOME/.m2

#use this distrib for actual java version
#dist: trusty

#matrix:
# include:
#  - os: linux
#    dist: trusty
#    sudo: required
#  - os: osx
#  - os: windows

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - alien
      
addons:
  sonarcloud:
    organization: "antonmykolaienko-github" # the key of the org you chose at step #3
    #token:
     # secure: ********* # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner

jdk:
 - oraclejdk8

script: mvn clean package