---
language: java

cache:
 directories:
  - $HOME/.m2

#use this distrib for actual java version
#dist: trusty

#matrix:
# include:
#  - os: linux
#    dist: trusty
#    sudo: required
#  - os: osx
#  - os: windows

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - alien

jdk:
 - oraclejdk8

script: mvn clean package