---
language: java

cache:
 directories:
  - $HOME/.m2

#use this distrib for actual java version
dist: trusty
 
#before_script:
# - jdk_switcher use oraclejdk8

jdk:
 - oraclejdk8

script: mvn clean package